import { Vacancy } from "../entities/Vacancy";

export let vacanciesList: Array<Vacancy> = [
    
    new Vacancy("Desenvolvedor de Software", "Pleno", "Manhã", "Presencial", "Responsável pelo desenvolvimento e manutenção de aplicativos web e móveis. Colabora com equipes multifuncionais para implementar soluções inovadoras. Experiência em linguagens de programação como JavaScript, Python e conhecimento em frameworks como React e Django é desejável.", "Especialistas em segurança cibernética: Protegemos o futuro digital das empresas, oferecendo soluções de segurança robustas e personalizadas para enfrentar os desafios da cibersegurança.", ["Wireshark", "Java", "Spring", "React", "OSSEC"]),
    new Vacancy("Analista de Marketing Digital", "Júnior", "Tarde", "Remoto", "Apoia na criação e execução de campanhas de marketing digital. Realiza análises de métricas de desempenho e identifica oportunidades de melhoria. Conhecimento básico em SEO, SEM e ferramentas de análise de dados é preferencial.", "Nossa empresa lidera o caminho em desenvolvimento de software, fornecendo soluções tecnológicas de ponta para impulsionar o crescimento dos negócios.", ["Ruby", "Java", "Spring", "React", "Angular"]),
    new Vacancy("Engenheiro de Dados", "Sênior", "Manhã", "Híbrido", "Projetar e implementar arquiteturas de dados escaláveis e eficientes. Desenvolver pipelines de ingestão, processamento e análise de grandes volumes de dados. Experiência em tecnologias como Apache Kafka, Hadoop e Spark é fundamental.", "Conduzindo a inovação tecnológica: Estamos na vanguarda da transformação digital, desenvolvendo soluções disruptivas que capacitam nossos clientes a se destacarem em um mercado competitivo.", ["Snort", "Java", "React", "C#"]),
    new Vacancy("Designer Gráfico", "Júnior", "Tarde", "Presencial", "Criação de materiais visuais para campanhas de marketing e comunicação corporativa. Colabora com equipes de marketing e produto para desenvolver conceitos criativos. Domínio de ferramentas como Adobe Photoshop, Illustrator e InDesign é necessário.", "Oferecemos suporte técnico especializado e soluções de infraestrutura confiáveis, permitindo que empresas concentrem-se em seu core business enquanto cuidamos de sua tecnologia.", ["Gradle", "Java", "C++", "Ruby", "OSSEC"]),
    new Vacancy("Analista Financeiro", "Pleno", "Manhã", "Híbrido", "Responsável pela análise e interpretação de dados financeiros. Elabora relatórios gerenciais e prevê tendências de desempenho financeiro. Experiência em modelagem financeira e ferramentas como Excel e SAP é valorizada.", "Conduzindo a inovação tecnológica: Estamos na vanguarda da transformação digital, desenvolvendo soluções disruptivas que capacitam nossos clientes a se destacarem em um mercado competitivo.", ["Snort", "Java", "React", "C#"])
]